### ISSUE TITLE
Валидация при создании Group

### ISSUE THREAD

**Issue by Ravshan89** [ESDP-C-5/ESDP#58]

**Comment by Ravshan89** [comment]
**Добавить валидацию в модели Group - 3 часа**

**Мотивация**
Захожу на страницу Group. Нажимаю добавить Group, ввожу данные, Нажимаю "Добавить". Наблюдаемое поведение: Добавляет группу, даже если поля пустые. Ожидаемое поведение:  поля должны быть обязательно заполнены пользователем.

**Причины**
Пользователь(Админ) не должен создавать пустые поля при добавлении новой группы

**Вариант решения**
Добавить валидацию в моделе Group

**Comment by maratik-tech** [comment]
done
