### ISSUE TITLE
Редактирование модели Group

### ISSUE THREAD

**Issue by Ravshan89** [ESDP-C-5/ESDP#62]

**Comment by Ravshan89** [comment]
**Отредактировать модель Group - 3 часа**

**Мотивация**
Нет надобности в Group иметь Name, LevelId, Level

**Причины**
 При встрече с заказчиком было понятно, что нужно изменить сущность Group

**Вариант решения**
Отредактировать модель Group, удалить поля:

1. Name
2. LevelId
3. Level


Добавить миграцию ModelGroupChange

**Comment by maratik-tech** [comment]
Done
